import { LocalClient } from "./src/local-client.js?v=34";

const api=new LocalClient(),$=s=>document.querySelector(s),money=v=>`¥${Number(v||0).toLocaleString("zh-CN")}`;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const states={in_stock:"在库",reserved:"已预订",sold_pending_pickup:"已售待取",sold:"已售",in_repair:"送修中"};
let currentUser=null,candidate=null,currentAppearance=null,lastIntake=null,currentInteraction=null,lastVoiceIntakeText="",toastTimer,appearanceBatch=[],currentWorklist="";
const defaultWarrantyTerms="质保期内，正常使用出现主板、屏幕显示或触控、摄像、听筒、扬声器、充电等非人为功能故障，请送回门店检测。确认属于质保范围后，由门店维修、换同等设备或协商处理。摔碰挤压、进液受潮、弯曲破裂、私自拆修、刷机越狱、账号锁或密码遗失、非原装配件造成的损坏，以及电池与外观的正常损耗，不属于门店质保。资料请自行备份，检测维修可能导致数据丢失；法律法规另有规定的，从其规定。";

function showRoot(id){["mobile-setup","mobile-login","mobile-app"].forEach(name=>$(`#${name}`).hidden=name!==id)}
function showPanel(id="home-panel"){$("#mobile-app").querySelectorAll(".panel").forEach(panel=>panel.hidden=panel.id!==id);window.scrollTo({top:0,behavior:"instant"})}
function toast(message){$("#m-toast").textContent=message;$("#m-toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#m-toast").classList.remove("show"),2400)}
function showDone(title,text,{handoff=null,device=null,customer=false}={}){lastIntake=device;$("#m-done-title").textContent=title;$("#m-done-text").textContent=text;const link=$("#m-handoff-link"),qrBox=$("#m-handoff-qr-box"),qr=$("#m-handoff-qr");link.hidden=!handoff;link.href=handoff?.url||"";qrBox.hidden=!handoff;qr.src=handoff?.qrUrl||"";$("#m-done-photo").hidden=!device;$("#m-done-customer").hidden=!customer;$("#m-done").hidden=false}

async function boot(){const setup=await api.setupStatus();if(!setup.configured)return showRoot("mobile-setup");try{currentUser=await api.me();await loadApp()}catch{showRoot("mobile-login")}}
async function loadApp(){showRoot("mobile-app");$("#mobile-shop-name").textContent=currentUser.shop_name;showPanel();await refreshSummary()}
async function refreshSummary(){const d=await api.dashboard();$("#m-active").textContent=`${d.activeCount} 台`;$("#m-intake").textContent=d.todayIntake;$("#m-sold").textContent=d.todaySold;$("#m-unprinted").textContent=d.unprintedCount;$("#m-pending").textContent=d.pendingCompletionCount;$("#m-photos").textContent=d.pendingPhotosCount||0;$("#m-customer-pending").textContent=d.pendingCustomerCount||0;$("#m-followup").textContent=d.followupDueCount||0;const reminder=$("#closing-reminder"),items=[];if(d.pendingCompletionCount)items.push(`${d.pendingCompletionCount}台待补全`);if(d.pendingPhotosCount)items.push(`${d.pendingPhotosCount}台待拍外观`);if(d.pendingCustomerCount)items.push(`${d.pendingCustomerCount}条成交待补`);if(d.unprintedCount)items.push(`${d.unprintedCount}台待打印`);reminder.hidden=new Date().getHours()<18||!items.length;reminder.textContent=`关店前提醒：${items.join("，")}。`}

function deviceCard(d){const pending=d.intake_state==="pending";return `<article class="device-card ${pending?"pending":""}"><div class="wide"><small>设备</small><strong>${esc(d.model)} · ${esc(d.storage)}</strong></div><div><small>库存编号</small><strong>${esc(d.stock_code)}</strong></div><div><small>状态</small><strong>${pending?"待补全":esc(states[d.status]||d.status)}</strong></div><div><small>IMEI尾号</small><strong>${esc(d.imei_tail||String(d.imei||"").slice(-4)||"-")}</strong></div><div><small>库位</small><strong>${esc(d.area||"-")}</strong></div><div class="wide"><small>当前标价</small><strong class="price">${money(d.list_price)}</strong></div></article>`}
function appearanceComplete(d){return Number(d.front_photo_count||0)>0&&Number(d.back_photo_count||0)>0&&d.appearance_status!=="pending"}
function appearanceLabel(d){const count=Number(d.photo_count||0),defects=Number(d.defect_photo_count||0);if(!appearanceComplete(d))return count?`外观照片未完成 · 已拍${count}张`:`未录入外观照片`;if(d.appearance_status==="complete_with_defect")return `外观已完成 · 瑕疵${defects}张 · 共${count}张`;return `外观已完成 · 无明显瑕疵 · ${count}张`}
function photoDetails(d){const parts=[["正面",d.front_photo_count],["背面",d.back_photo_count],["边框",d.frame_photo_count],["瑕疵",d.defect_photo_count]].filter(([,count])=>Number(count)>0).map(([name,count])=>`${name}${count}`);return parts.length?parts.join(" · "):"还没有外观照片"}
function simpleDeviceDescription(d){const parts=[d.color,d.condition_grade,d.battery_health!==null&&d.battery_health!==undefined&&d.battery_health!==""?`电池${d.battery_health}%`:"",d.area?`库位${d.area}`:""].filter(Boolean);const note=String(d.notes||"").trim();if(note)parts.push(note.length>56?`${note.slice(0,56)}…`:note);return parts.join(" · ")||"暂无机况描述"}
function deviceRows(rows,{pending=false,inventory=false}={}){return rows.length?rows.map(d=>{const printed=d.print_status==="printed",sold=d.status==="sold";return `<article class="mobile-item ${pending||inventory?"actionable":""} ${inventory?"inventory-item":""}" ${pending?`data-complete-device="${esc(d.id)}"`:""}><span><strong>${esc(d.model)} · ${esc(d.storage)}</strong><small>${esc(d.stock_code)} · IMEI尾号 ${esc(d.imei_tail||"-")}</small>${inventory?`<small class="device-description">${esc(simpleDeviceDescription(d))}</small><i class="photo-state ${appearanceComplete(d)?"complete":"pending"}">${esc(appearanceLabel(d))}</i><small class="photo-detail">${esc(photoDetails(d))}</small><i class="print-state ${printed?"printed":""}">${printed?"打印任务成功":"未成功打印"}</i>`:`<i class="state ${d.intake_state==="pending"?"pending":""}">${d.intake_state==="pending"?"待补全":esc(states[d.status]||d.status)}</i>`}</span><b>${money(d.list_price)}</b>${inventory?(sold?`<div class="inventory-actions locked-record">已出库，资料与照片已锁定，只能查看</div>`:`<div class="inventory-actions"><button type="button" data-photo-device="${esc(d.id)}">${appearanceComplete(d)?"增加照片":"补拍外观"}</button><button type="button" data-print-device="${esc(d.id)}">${printed?"重新打印":"打印标签"}</button></div>`):""}</article>`}).join(""):`<div class="notice">没有找到设备</div>`}
async function loadInventory(query=""){$("#m-search-results").innerHTML='<div class="notice">正在读取库存…</div>';$("#m-search-results").innerHTML=deviceRows(await api.devices(query,"all"),{inventory:true})}
async function loadWorklist(task){currentWorklist=task;showPanel("worklist-panel");const config={pending_photos:["待拍外观","这些手机缺少正面、背面或尚未完成外观留档。点击“补拍外观”即可处理。"],unprinted:["待打印标签","系统未收到成功的打印任务结果。检查打印机出纸后，可逐台点击打印。"],followup:["待跟进客户","到期需要回访的顾客记录。点击一条记录，可查看原始速记并补充跟进结果。"]},[title,help]=config[task]||["待办列表",""];$("#worklist-title").textContent=title;$("#worklist-help").textContent=help;const box=$("#worklist-results");box.innerHTML='<div class="notice">正在读取待办…</div>';if(task==="followup"){const rows=await api.customerTasks("followup");box.innerHTML=rows.length?interactionRows(rows,true):'<div class="worklist-empty">目前没有到期跟进，已经清空。</div>'}else{const rows=await api.devices("",task);box.innerHTML=rows.length?deviceRows(rows,{inventory:true}):'<div class="worklist-empty">目前没有这类待办，已经清空。</div>'}}
async function openPanel(id){if(id!=="worklist-panel")currentWorklist="";showPanel(id);if(id==="scan-panel")resetScan();if(id==="search-panel")await loadInventory($("#m-search").value.trim());if(id==="pending-panel")await loadPending();if(id==="customer-panel")await loadCustomerCenter();if(id==="worklist-panel"&&currentWorklist)await loadWorklist(currentWorklist)}

async function imageData(file){const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,1800/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",.82)}finally{URL.revokeObjectURL(url)}}
async function scanImageData(file){if(/^image\/(jpeg|jpg|png|webp)$/i.test(file.type||"")&&file.size<=9_500_000)return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("照片读取失败"));reader.readAsDataURL(file)});return imageData(file)}

function resetVoiceIntake(){$("#voice-intake-text").value="";$("#voice-intake-result").hidden=true;$("#voice-intake-result").innerHTML="";lastVoiceIntakeText=""}
async function submitIntake(form,quick=false){const button=form.querySelector("button[type=submit]"),error=$(quick?"#quick-error":"#full-error");button.disabled=true;error.textContent="";try{const data=Object.fromEntries(new FormData(form));if(!quick&&lastVoiceIntakeText)data.sourceFields={mode:"mobile_voice_text",originalText:lastVoiceIntakeText};let result;try{result=quick?await api.quickIntake(data):await api.intake(data)}catch(e){if(!quick&&e.message.includes("销售标价低于收货成本")&&confirm("销售标价低于收货成本，仍要入库吗？")){data.allowBelowCost=true;result=await api.intake(data)}else throw e}let printText="，已交给电脑打印";try{await api.printLabel(result.id)}catch(e){printText=`，入库成功但打印失败：${e.message}`}form.reset();if(!quick)resetVoiceIntake();showDone(quick?"快速入库完成":"完整入库完成",`${result.stockCode}${printText}`,{device:{id:result.id,stockCode:result.stockCode},customer:true});await refreshSummary()}catch(e){error.textContent=e.message}finally{button.disabled=false}}

function fillVoiceIntake(result){const form=$("#full-form"),mapping={brand:"brand",model:"model",storage:"storage",imei:"imei",purchaseCost:"purchaseCost",listPrice:"listPrice",color:"color",conditionGrade:"conditionGrade",systemVersion:"systemVersion",batteryHealth:"batteryHealth",chargeCycles:"chargeCycles",area:"area",notes:"notes"};for(const [key,name] of Object.entries(mapping)){const value=result[key];if(value!==null&&value!==undefined&&String(value).trim()!==""&&form.elements[name])form.elements[name].value=value}const required=[["brand","品牌"],["model","型号"],["storage","容量"],["imei","IMEI"],["purchaseCost","收货成本"],["listPrice","销售标价"]],missing=required.filter(([name])=>!String(form.elements[name]?.value||"").trim()).map(([,label])=>label);const chips=required.map(([name,label])=>`<span class="${form.elements[name]?.value?"ok":"missing"}">${esc(label)}：${esc(form.elements[name]?.value||"未识别")}</span>`).join("");const box=$("#voice-intake-result");box.hidden=false;box.innerHTML=`<b>${missing.length?"已识别，请补充后核对":"核心资料已识别，请核对后入库"}</b><div>${chips}</div>${missing.length?`<small>还缺：${esc(missing.join("、"))}</small>`:"<small>识别结果不会自动入库，必须由你点击确认。</small>"}`;form.scrollIntoView({behavior:"smooth",block:"start"})}

async function loadPending(){$("#m-pending-list").innerHTML=deviceRows(await api.devices("","pending_completion"),{pending:true})}
async function openCompletion(id){const d=await api.device(id),form=$("#completion-form");form.reset();currentAppearance={id:d.id,stockCode:d.stock_code};$("#completion-title").textContent=`补全 ${d.stock_code}`;for(const [name,key] of Object.entries({brand:"brand",model:"model",storage:"storage",imei:"imei",listPrice:"list_price",purchaseCost:"purchase_cost",color:"color",conditionGrade:"condition_grade",systemVersion:"system_version",batteryHealth:"battery_health",area:"area",notes:"notes"})){if(form.elements[name])form.elements[name].value=d[key]??""}form.elements.id.value=d.id;form.elements.purchaseCost.disabled=currentUser.role!=="owner";showPanel("completion-panel")}

function clearAppearanceBatch(){appearanceBatch.forEach(item=>URL.revokeObjectURL(item.url));appearanceBatch=[];const input=$("#appearance-batch-input");if(input)input.value="";renderAppearanceBatch()}
function renderAppearanceBatch(){const box=$("#appearance-batch-preview"),button=$("#appearance-save-all");if(!box||!button)return;if(!appearanceBatch.length){box.innerHTML='<div class="notice">还没有选择照片</div>';button.disabled=true;button.textContent="保存全部照片";return}const names={front:"正面",back:"背面",frame:"边框",defect:"瑕疵",other:"其他"};box.innerHTML=appearanceBatch.map((item,index)=>`<article class="photo-batch-item ${item.saved?"saved":""}" data-photo-index="${index}"><img src="${esc(item.url)}" alt="第 ${index+1} 张外观照片"><select aria-label="第 ${index+1} 张照片分类" ${item.saved?"disabled":""}>${Object.entries(names).map(([value,label])=>`<option value="${value}" ${item.type===value?"selected":""}>${label}</option>`).join("")}</select>${item.saved?"":'<button type="button" aria-label="移除这张照片">×</button>'}</article>`).join("");button.disabled=!appearanceBatch.some(item=>!item.saved);button.textContent=appearanceBatch.some(item=>item.saved)?"保存剩余照片":"保存全部照片"}
async function openAppearance(device){currentAppearance=typeof device==="string"?{id:device,...await api.device(device)}:device;$("#appearance-device").textContent=`${currentAppearance.stockCode||currentAppearance.stock_code||""}：请一次选择全部照片；正面、背面必拍，有瑕疵请把对应照片分类改为“瑕疵”。`;$("#appearance-error").textContent="";$("#appearance-progress").innerHTML="";$("#appearance-panel").querySelectorAll("input[type=file]").forEach(i=>i.value="");clearAppearanceBatch();showPanel("appearance-panel")}
function addPhotoProgress(type,text,done=false){const map={front:"正面",back:"背面",frame:"边框",defect:"瑕疵",other:"其他"},row=document.createElement("span");row.className=done?"done":"";row.dataset.photoType=type;row.textContent=`${map[type]}：${text}`;$("#appearance-progress").append(row)}
async function autoConfirmAppearance(){const detail=await api.device(currentAppearance.id),types=new Set((detail.photos||[]).map(photo=>photo.photo_type));if(types.has("front")&&types.has("back")){await api.confirmAppearance(currentAppearance.id,types.has("defect")?"defect_documented":"no_obvious_defect");return true}return false}

async function resolveCode(raw){const code=String(raw||"").trim();if(!code)return;$("#m-scan-error").textContent="正在匹配库存…";try{const matches=await api.devices(code,""),normalized=code.toLowerCase(),exact=matches.filter(d=>String(d.stock_code||"").toLowerCase()===normalized||String(d.imei||"")===code),found=exact.length===1?exact[0]:(!exact.length&&matches.length===1?matches[0]:null);if(!found)throw new Error(matches.length>1?"找到多台相似设备，请输入完整编号":"没有找到对应库存");candidate={...found,...await api.device(found.id)};$("#m-device-card").innerHTML=deviceCard(candidate);const form=$("#m-sale-form");form.reset();form.elements.deviceId.value=candidate.id;form.elements.salePrice.value=candidate.list_price;form.elements.warrantyDays.value=30;form.elements.warrantyTerms.value=defaultWarrantyTerms;form.elements.handoffDisclosure.value=[candidate.condition_grade?`成色：${candidate.condition_grade}`:"",candidate.notes||""].filter(Boolean).join("；");form.elements.handoffUnchecked.value="未拆机检查内部防水状态；未长期测试待机耗电。";const canSell=["in_stock","reserved","sold_pending_pickup"].includes(candidate.status)&&candidate.intake_state!=="pending";$("#m-confirm-sale").disabled=!canSell;$("#m-scan-error").textContent=canSell?"":"这台手机仍在待补全，不能出库";$("#m-scan-start").hidden=true;$("#m-sale-match").hidden=false}catch(e){$("#m-scan-error").textContent=e.message}}
function resetScan(){candidate=null;$("#m-scan-start").hidden=false;$("#m-sale-match").hidden=true;$("#m-scan-form").reset();$("#m-sale-form").reset();$("#m-scan-error").textContent=""}

function interactionRows(rows,followup=false){return rows.length?rows.map(r=>`<article class="mobile-item actionable" data-interaction="${esc(r.id)}"><span><strong>${esc(r.display_name||r.model||"匿名客户")}</strong><small>${esc(r.stock_code||r.interaction_type)} · ${new Date(r.occurred_at).toLocaleString("zh-CN")}</small><small>${esc(r.raw_note||r.source_channel||"等待补充")}</small></span><b>${followup?"跟进":"补齐"}</b></article>`).join(""):`<div class="notice">当前没有记录</div>`}
async function loadCustomerCenter(){const [tasks,followups]=await Promise.all([api.customerTasks("pending"),api.customerTasks("followup")]);$("#customer-task-list").innerHTML=interactionRows(tasks);$("#followup-list").innerHTML=interactionRows(followups,true)}
function clearInteractionForm(){const form=$("#interaction-form");form.reset();form.elements.id.value="";form.elements.deviceId.value="";form.elements.rawNote.readOnly=false;$("#interaction-dismiss").hidden=true;$("#note-warnings").hidden=true;currentInteraction=null}
async function openInteraction(id=null,defaults={}){clearInteractionForm();const form=$("#interaction-form");if(id){const d=await api.customerInteraction(id);currentInteraction=d;$("#interaction-title").textContent=d.sale_id?"补成交客户记录":"编辑客户记录";form.elements.id.value=d.id;form.elements.deviceId.value=d.device_id||"";form.elements.interactionType.value=d.interaction_type;form.elements.rawNote.value=d.raw_note||"";form.elements.rawNote.readOnly=true;for(const [name,key] of Object.entries({displayName:"display_name",phone:"phone",sourceChannel:"source_channel",budgetMax:"budget_max",preferredBrand:"preferred_brand",preferredModel:"preferred_model",preferredStorage:"preferred_storage",outcome:"outcome",lostReason:"lost_reason",confirmedSummary:"confirmed_summary"}))if(form.elements[name])form.elements[name].value=d[key]??"";form.elements.concerns.value=(d.concerns||[]).join("、");if(d.next_followup_at)form.elements.nextFollowupAt.value=new Date(d.next_followup_at).toISOString().slice(0,16);$("#interaction-dismiss").hidden=false}else{$("#interaction-title").textContent=defaults.title||"新增到店记录";form.elements.interactionType.value=defaults.interactionType||"inquiry";form.elements.deviceId.value=defaults.deviceId||""}showPanel("interaction-panel")}
function fillSuggestions(s){const f=$("#interaction-form");for(const [name,key] of Object.entries({budgetMax:"budgetMax",preferredBrand:"preferredBrand",preferredModel:"preferredModel",preferredStorage:"preferredStorage",sourceChannel:"sourceChannel",lostReason:"lostReason",nextFollowupAt:"nextFollowupAt"})){const value=s[key];if(value&&!f.elements[name].value)f.elements[name].value=name==="nextFollowupAt"?new Date(value).toISOString().slice(0,16):value}if(s.concerns?.length&&!f.elements.concerns.value)f.elements.concerns.value=s.concerns.join("、")}

$("#mobile-login-form").addEventListener("submit",async e=>{e.preventDefault();$("#mobile-login-error").textContent="";const d=Object.fromEntries(new FormData(e.currentTarget));try{await api.login(d.username,d.password);currentUser=await api.me();await loadApp()}catch(error){$("#mobile-login-error").textContent=error.message}});
$("#mobile-logout").addEventListener("click",async()=>{await api.logout();currentUser=null;showRoot("mobile-login")});
document.addEventListener("click",async e=>{const task=e.target.closest("[data-task]");if(task){await loadWorklist(task.dataset.task);return}const open=e.target.closest("[data-open]");if(open){await openPanel(open.dataset.open);return}if(e.target.closest("[data-back]")){await openPanel();await refreshSummary();return}const photo=e.target.closest("[data-photo-device]");if(photo){await openAppearance(photo.dataset.photoDevice);return}const print=e.target.closest("[data-print-device]");if(print){const original=print.textContent;print.disabled=true;print.textContent="正在打印…";try{await api.printLabel(print.dataset.printDevice);toast("打印任务成功，请确认标签已经出纸");if(currentWorklist)await loadWorklist(currentWorklist);else await loadInventory($("#m-search").value.trim());await refreshSummary()}catch(error){toast(`打印失败：${error.message}`);print.disabled=false;print.textContent=original}return}const pending=e.target.closest("[data-complete-device]");if(pending){await openCompletion(pending.dataset.completeDevice);return}const interaction=e.target.closest("[data-interaction]");if(interaction){await openInteraction(interaction.dataset.interaction)}});

$("#voice-intake-parse").addEventListener("click",async()=>{const text=$("#voice-intake-text").value.trim(),button=$("#voice-intake-parse");if(!text)return toast("请先用语音或文字描述手机资料");button.disabled=true;button.textContent="正在本地识别…";$("#full-error").textContent="";try{const result=await api.parseIntake(text);lastVoiceIntakeText=text;fillVoiceIntake(result);toast("已识别并填入，请核对后入库")}catch(error){$("#full-error").textContent=error.message}finally{button.disabled=false;button.textContent="识别信息并填入"}});

$("#full-form").addEventListener("submit",e=>{e.preventDefault();submitIntake(e.currentTarget,false)});
$("#completion-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,data=Object.fromEntries(new FormData(f)),id=data.id;delete data.id;data.markComplete=true;$("#completion-error").textContent="";try{await api.updateDevice(id,data);toast("资料已补全，现在可以出售");await openAppearance({id,stockCode:currentAppearance.stockCode});await refreshSummary()}catch(error){$("#completion-error").textContent=error.message}});

$("#m-scan-photo").addEventListener("click",()=>$("#m-scan-file").click());$("#m-scan-file").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;$("#m-scan-error").textContent="正在识别二维码…";try{const result=await api.recognizeQr(await scanImageData(file));await resolveCode(result.value)}catch(error){$("#m-scan-error").textContent=error.message}finally{e.target.value=""}});$("#m-scan-form").addEventListener("submit",async e=>{e.preventDefault();await resolveCode($("#m-scan-code").value)});$("#m-rescan").addEventListener("click",resetScan);
$("#m-sale-form").addEventListener("submit",async e=>{e.preventDefault();if(!candidate)return;const b=$("#m-confirm-sale");b.disabled=true;b.textContent="正在出库…";try{const result=await api.sell(candidate.id,Object.fromEntries(new FormData(e.currentTarget)));showDone("出库完成",`${candidate.model} · ${candidate.stock_code} 已出库；已生成一条待补客户记录`,{handoff:result.handoff});await refreshSummary()}catch(error){$("#m-scan-error").textContent=error.message}finally{b.disabled=false;b.textContent="确认出库"}});
$("#m-search-form").addEventListener("submit",async e=>{e.preventDefault();await loadInventory($("#m-search").value.trim())});

$("#appearance-batch-input").addEventListener("change",e=>{const files=[...e.target.files].slice(0,20);appearanceBatch.forEach(item=>URL.revokeObjectURL(item.url));appearanceBatch=files.map((file,index)=>({file,url:URL.createObjectURL(file),type:index===0?"front":index===1?"back":"frame",saved:false}));$("#appearance-error").textContent=e.target.files.length>20?"一次最多保存 20 张，已选取前 20 张。":"";renderAppearanceBatch()});
$("#appearance-batch-preview").addEventListener("change",e=>{const item=e.target.closest("[data-photo-index]");if(!item||e.target.tagName!=="SELECT")return;appearanceBatch[Number(item.dataset.photoIndex)].type=e.target.value});
$("#appearance-batch-preview").addEventListener("click",e=>{const remove=e.target.closest("button"),item=e.target.closest("[data-photo-index]");if(!remove||!item)return;const index=Number(item.dataset.photoIndex);URL.revokeObjectURL(appearanceBatch[index].url);appearanceBatch.splice(index,1);renderAppearanceBatch()});
$("#appearance-save-all").addEventListener("click",async()=>{const button=$("#appearance-save-all"),pending=appearanceBatch.filter(item=>!item.saved);if(!pending.length)return;button.disabled=true;button.textContent=`正在保存 0 / ${pending.length}`;$("#appearance-error").textContent="";$("#appearance-progress").innerHTML="";let saved=0;try{for(const item of pending){button.textContent=`正在保存 ${saved+1} / ${pending.length}`;await api.addPhoto(currentAppearance.id,{photoType:item.type,image:await imageData(item.file),description:"手机外观留档"});item.saved=true;saved+=1;addPhotoProgress(item.type,`第 ${saved} 张已保存`,true);renderAppearanceBatch()}const complete=await autoConfirmAppearance();toast(complete?`${saved} 张照片已保存，外观留档已自动完成`:`${saved} 张照片已保存，还缺正面或背面`);await refreshSummary()}catch(error){$("#appearance-error").textContent=`已保存 ${saved} 张；${error.message}。可以点击“保存剩余照片”继续。`}finally{renderAppearanceBatch()}});
document.querySelectorAll(".photo-input").forEach(input=>input.addEventListener("change",async e=>{const files=[...e.target.files],type=e.target.dataset.type;if(!files.length)return;addPhotoProgress(type,"正在压缩并保存…");try{for(const file of files)await api.addPhoto(currentAppearance.id,{photoType:type,image:await imageData(file),description:"手机外观留档"});addPhotoProgress(type,`已保存 ${files.length} 张`,true);const complete=await autoConfirmAppearance();toast(complete?"照片已保存，外观留档已自动完成":"照片已保存，还缺正面或背面");await refreshSummary()}catch(error){$("#appearance-error").textContent=error.message}finally{e.target.value=""}}));

$("#new-interaction").addEventListener("click",()=>openInteraction());$("#customer-search-button").addEventListener("click",()=>{$("#customer-search-box").hidden=!$("#customer-search-box").hidden});$("#customer-search-form").addEventListener("submit",async e=>{e.preventDefault();const rows=await api.customers(new FormData(e.currentTarget).get("q"));$("#customer-search-results").innerHTML=rows.length?rows.map(c=>`<article class="mobile-item"><span><strong>${esc(c.display_name||"未填写称呼")}</strong><small>${esc(c.phone||"无手机号")} · ${c.interaction_count}次互动</small></span><b>${c.status==="active"?"在用":"已匿名"}</b></article>`).join(""):`<div class="notice">没有找到客户</div>`});
$("#parse-note").addEventListener("click",async()=>{const text=$("#interaction-form").elements.rawNote.value;if(!text)return toast("请先输入或语音转写速记");try{const r=await api.parseCustomerNote(text);fillSuggestions(r.suggestions);const box=$("#note-warnings");box.hidden=!r.warnings.length;box.textContent=r.warnings.join("；");toast("已填入本地整理建议，请确认后保存")}catch(e){$("#interaction-error").textContent=e.message}});
$("#interaction-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,data=Object.fromEntries(new FormData(f));data.consent=!!f.elements.consent.checked;data.concerns=data.concerns||"";$("#interaction-error").textContent="";try{if(data.id){const id=data.id;delete data.id;delete data.rawNote;await api.completeCustomerInteraction(id,data)}else{delete data.id;data.complete=true;await api.createCustomerInteraction(data)}toast("客户记录已保存");await openPanel("customer-panel");await refreshSummary()}catch(error){$("#interaction-error").textContent=error.message}});$("#interaction-dismiss").addEventListener("click",async()=>{const id=$("#interaction-form").elements.id.value;if(!id)return;try{await api.completeCustomerInteraction(id,{dismissed:true});toast("已标记无需补充");await openPanel("customer-panel");await refreshSummary()}catch(e){$("#interaction-error").textContent=e.message}});

$("#m-done-photo").addEventListener("click",async()=>{$("#m-done").hidden=true;await openAppearance(lastIntake)});$("#m-done-customer").addEventListener("click",()=>{$("#m-done").hidden=true;openInteraction(null,{title:"记录卖机客户",interactionType:"sell_to_store",deviceId:lastIntake?.id||""})});$("#m-done-home").addEventListener("click",async()=>{$("#m-done").hidden=true;await openPanel();await refreshSummary()});

boot().catch(error=>{showRoot("mobile-login");$("#mobile-login-error").textContent=error.message});setInterval(()=>{if(currentUser&&document.visibilityState==="visible")refreshSummary().catch(()=>{})},10000);
if("serviceWorker" in navigator&&(location.protocol==="https:"||location.hostname==="127.0.0.1"||location.hostname==="localhost"))navigator.serviceWorker.register("/sw.js").catch(()=>{});
