import { LocalClient } from "./src/local-client.js?v=32";

const api = new LocalClient();
const $ = selector => document.querySelector(selector);
const money = value => `¥${Number(value || 0).toLocaleString("zh-CN")}`;
const esc = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const states = {in_stock:"在库",reserved:"已预订",sold_pending_pickup:"已售待取",sold:"已售",in_repair:"送修中"};
let currentUser = null;
let candidate = null;
let toastTimer;

function showRoot(id){["mobile-setup","mobile-login","mobile-app"].forEach(name=>$(`#${name}`).hidden=name!==id);}
function showPanel(id="home-panel"){$("#mobile-app").querySelectorAll(".panel").forEach(panel=>panel.hidden=panel.id!==id);window.scrollTo({top:0,behavior:"instant"});}
function toast(message){$("#m-toast").textContent=message;$("#m-toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#m-toast").classList.remove("show"),2200);}
function showDone(title,text,handoff){$("#m-done-title").textContent=title;$("#m-done-text").textContent=text;const link=$("#m-handoff-link");link.hidden=!handoff;link.href=handoff?.url||"";$("#m-done").hidden=false;}

async function boot(){const setup=await api.setupStatus();if(!setup.configured)return showRoot("mobile-setup");try{currentUser=await api.me();await loadApp();}catch{showRoot("mobile-login");}}
async function loadApp(){showRoot("mobile-app");$("#mobile-shop-name").textContent=currentUser.shop_name;showPanel();await refreshSummary();}
async function refreshSummary(){const dash=await api.dashboard();$("#m-active").textContent=`${dash.activeCount} 台`;$("#m-intake").textContent=dash.todayIntake;$("#m-sold").textContent=dash.todaySold;$("#m-reserved").textContent=dash.reservedCount;$("#m-pickup").textContent=dash.pendingPickupCount;$("#m-unprinted").textContent=dash.unprintedCount;$("#m-pending").textContent=dash.pendingCompletionCount;const reminder=$("#closing-reminder");const afterClosing=new Date().getHours()>=18;const items=[];if(dash.pendingCompletionCount)items.push(`${dash.pendingCompletionCount}台待补全`);if(dash.unprintedCount)items.push(`${dash.unprintedCount}台待打印`);reminder.hidden=!afterClosing||!items.length;reminder.textContent=`关店前提醒：${items.join("，")}。`}

function deviceCard(device){const pending=device.intake_state==="pending";return `<article class="device-card ${pending?"pending":""}"><div class="wide"><small>设备</small><strong>${esc(device.model)} · ${esc(device.storage)}</strong></div><div><small>库存编号</small><strong>${esc(device.stock_code)}</strong></div><div><small>状态</small><strong>${pending?"待补全":esc(states[device.status]||device.status)}</strong></div><div><small>IMEI尾号</small><strong>${esc(device.imei_tail||String(device.imei||"").slice(-4)||"-")}</strong></div><div><small>库位</small><strong>${esc(device.area||"-")}</strong></div><div class="wide"><small>当前标价</small><strong class="price">${money(device.list_price)}</strong></div></article>`;}
function listHtml(rows){return rows.length?rows.map(d=>`<article class="mobile-item"><span><strong>${esc(d.model)} · ${esc(d.storage)}</strong><small>${esc(d.stock_code)} · IMEI尾号 ${esc(d.imei_tail||"-")}</small><i class="state ${d.intake_state==="pending"?"pending":""}">${d.intake_state==="pending"?"待补全":esc(states[d.status]||d.status)}</i></span><b>${money(d.list_price)}</b></article>`).join(""):`<div class="notice">没有找到设备</div>`;}

async function scanImageData(file){if(/^image\/(jpeg|jpg|png|webp)$/i.test(file.type||"")&&file.size<=9_500_000)return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("照片读取失败"));reader.readAsDataURL(file);});const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,3200/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",.94);}finally{URL.revokeObjectURL(url);}}
async function resolveCode(raw){const code=String(raw||"").trim();if(!code)return;$("#m-scan-error").textContent="正在匹配库存…";try{const matches=await api.devices(code,"");const normalized=code.toLowerCase();const exact=matches.filter(d=>String(d.stock_code||"").toLowerCase()===normalized||String(d.imei||"")===code);const found=exact.length===1?exact[0]:(!exact.length&&matches.length===1?matches[0]:null);if(!found)throw new Error(matches.length>1?"找到多台相似设备，请输入完整编号":"没有找到对应库存");candidate={...found,...await api.device(found.id)};$("#m-device-card").innerHTML=deviceCard(candidate);const form=$("#m-sale-form");form.reset();form.elements.deviceId.value=candidate.id;form.elements.salePrice.value=candidate.list_price;form.elements.warrantyDays.value=30;const canSell=["in_stock","reserved","sold_pending_pickup"].includes(candidate.status)&&candidate.intake_state!=="pending";$("#m-confirm-sale").disabled=!canSell;$("#m-scan-error").textContent=canSell?"":"这台手机仍在待补全，不能出库";$("#m-scan-start").hidden=true;$("#m-sale-match").hidden=false;}catch(error){$("#m-scan-error").textContent=error.message;}}
function resetScan(){candidate=null;$("#m-scan-start").hidden=false;$("#m-sale-match").hidden=true;$("#m-scan-form").reset();$("#m-sale-form").reset();$("#m-scan-error").textContent="";}

$("#mobile-login-form").addEventListener("submit",async event=>{event.preventDefault();$("#mobile-login-error").textContent="";const d=Object.fromEntries(new FormData(event.currentTarget));try{await api.login(d.username,d.password);currentUser=await api.me();await loadApp();}catch(error){$("#mobile-login-error").textContent=error.message;}});
$("#mobile-logout").addEventListener("click",async()=>{await api.logout();currentUser=null;showRoot("mobile-login");});
document.addEventListener("click",async event=>{const open=event.target.closest("[data-open]");if(open){showPanel(open.dataset.open);if(open.dataset.open==="scan-panel")resetScan();if(open.dataset.open==="pending-panel"){const rows=await api.devices("","pending_completion");$("#m-pending-list").innerHTML=listHtml(rows);}return;}if(event.target.closest("[data-back]")){showPanel();await refreshSummary();}});
$("#m-scan-photo").addEventListener("click",()=>$("#m-scan-file").click());
$("#m-scan-file").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;$("#m-scan-error").textContent="正在识别二维码…";try{const result=await api.recognizeQr(await scanImageData(file));await resolveCode(result.value);}catch(error){$("#m-scan-error").textContent=error.message;}finally{event.target.value="";}});
$("#m-scan-form").addEventListener("submit",async event=>{event.preventDefault();await resolveCode($("#m-scan-code").value);});
$("#m-rescan").addEventListener("click",resetScan);
$("#m-sale-form").addEventListener("submit",async event=>{event.preventDefault();if(!candidate)return;const button=$("#m-confirm-sale");button.disabled=true;button.textContent="正在出库…";try{const data=Object.fromEntries(new FormData(event.currentTarget));const result=await api.sell(candidate.id,data);showDone("出库完成",`${candidate.model} · ${candidate.stock_code} 已出库`,result.handoff);await refreshSummary();}catch(error){$("#m-scan-error").textContent=error.message;}finally{button.disabled=false;button.textContent="确认出库";}});
$("#quick-form").addEventListener("submit",async event=>{event.preventDefault();const button=$("#quick-submit");button.disabled=true;button.textContent="正在保存…";$("#quick-error").textContent="";$("#quick-result").hidden=true;try{const result=await api.quickIntake(Object.fromEntries(new FormData(event.currentTarget)));let printText="";try{await api.printLabel(result.id);printText="，待复检标签已打印";}catch(error){printText=`，已入库但打印失败：${error.message}`;}event.currentTarget.reset();showDone("快速入库完成",`${result.stockCode} 已建立${printText}`);await refreshSummary();}catch(error){$("#quick-error").textContent=error.message;}finally{button.disabled=false;button.textContent="保存并生成待复检标签";}});
$("#m-search-form").addEventListener("submit",async event=>{event.preventDefault();const rows=await api.devices($("#m-search").value.trim(),"all");$("#m-search-results").innerHTML=listHtml(rows);});
$("#m-done-home").addEventListener("click",async()=>{$("#m-done").hidden=true;showPanel();await refreshSummary();});

boot().catch(error=>{showRoot("mobile-login");$("#mobile-login-error").textContent=error.message;});
setInterval(()=>{if(currentUser&&document.visibilityState==="visible")refreshSummary().catch(()=>{});},10000);
